[package]
name = "file-trackr"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dunce = "1"
clap = { version ="4", features = ["derive"] }
colored = "2"
chrono = "0.4"
shell-words = "1"
